remote_theme: bcc-code/bcc-docs-theme
plugins:
- jekyll-remote-theme

collections:
  products:
    output: true
  docs:
    output: true
  guides:
    output: true
  topics:
    output: true
  plugins:
    output: true
  apis:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"