name: ADR - new issue created

on:
  issues:
    types: [opened]

jobs:
  comment:
    if: ${{ contains(github.event.issue.labels.*.name, 'adr') }}
    runs-on: ubuntu-latest

    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            **Remember that ADRs are publicly available hence do not include any confidential information in the issue description!**
            To read more about ADR please refer to [documentation](https://bcc-code.github.io/docs/ADL/).
