# This workflow creates a ADR based on a issue description on a issue close event.

name: Create ADR

on:
  issues: 
    types: [closed]

jobs:
  create_adr:
    if: ${{ contains(github.event.issue.labels.*.name, 'adr') }}
    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Convert title
        run: |
          title=${{ github.event.issue.title }}
          replacement="_"
          echo "${title//[\[\] ]/"$replacement"}" 

      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: ${{ format('docs/ADL/{0}_{1}.md', steps.date.outputs.date,  github.event.issue.title) }}
          FILE_DATA: ${{ github.event.issue.body }}

      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
