# This workflow creates a ADR based on a issue description on a issue close event.

name: Create ADR

# Controls when the workflow will run
on:
  issues: 
    types: [closed]


jobs:
  create_adr:
    if: ${{ github.event.issue.label.name == 'adr' }}

    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"

